solver_id: bsma_numba
solver_class: BSMANumbaSolver
capabilities:
  problem_types: [mkp]
  encodings: [binary]
  directions: [max]
stop_condition:
  type: max_iterations
  max_iterations: 5000
  max_seconds: null
params:
  - pop_size: 20
    z: 0.01
    ctf: tanh_abs
  - pop_size: 20
    z: 0.08
    ctf: tanh_abs
  - pop_size: 20
    z: 0.15
    ctf: tanh_abs

  - pop_size: 20
    z: 0.01
    ctf: sigmoid_s0
  - pop_size: 20
    z: 0.08
    ctf: sigmoid_s0
  - pop_size: 20
    z: 0.15
    ctf: sigmoid_s0

  - pop_size: 20
    z: 0.01
    ctf: abs_pow_16
  - pop_size: 20
    z: 0.08
    ctf: abs_pow_16
  - pop_size: 20
    z: 0.15
    ctf: abs_pow_16
